---
##
# setup:
# > pre-commit install --color auto --hook-type pre-commit --hook-type commit-msg
# update:
# > pre-commit autoupdate
##

# yamllint disable rule:line-length

repos:
  - repo: meta
    hooks:
      #- id: check-hooks-apply
      - id: check-useless-excludes
        name: Check for useless excludes (pre-commit)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        name: Check for merge conflicts (pre-commit)
      #- id: check-toml
      - id: check-xml
        name: Check xml (pre-commit)
      - id: end-of-file-fixer
        name: Fix end of files (pre-commit)
      - id: trailing-whitespace
        name: Trim trailing whitespace (pre-commit)
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        name: Check markdown (markdownlint-cli2)
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        name: Check Dockerfiles (hadolint)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: Check yaml (yamllint)
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: Check Shell scripts files (shellcheck)
#  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
#    rev: v9.18.0
#    hooks:
#      - id: commitlint
#        name: Check commit message (commitlint)
#        stages: [commit-msg]
#        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets (Gitleaks)
  - repo: https://github.com/scop/wrun
    rev: v0.4.0
    hooks:
      - id: wrun
        name: Detect hardcoded secrets (TruffleHog)
        #info command: trufflehog --no-update git file://. --since-commit HEAD --results=verified --fail
        pass_filenames: false
        # wrun generate github trufflesecurity trufflehog
        args: [
          --url, linux/amd64=https://github.com/trufflesecurity/trufflehog/releases/download/v3.88.13/trufflehog_3.88.13_linux_amd64.tar.gz,     # renovate: datasource=github-releases depName=trufflesecurity/trufflehog
          --url, linux/arm64=https://github.com/trufflesecurity/trufflehog/releases/download/v3.88.13/trufflehog_3.88.13_linux_arm64.tar.gz,     # renovate: datasource=github-releases depName=trufflesecurity/trufflehog
          --url, windows/amd64=https://github.com/trufflesecurity/trufflehog/releases/download/v3.88.13/trufflehog_3.88.13_windows_amd64.tar.gz, # renovate: datasource=github-releases depName=trufflesecurity/trufflehog
          --archive-exe-path, linux/amd64=trufflehog,
          --archive-exe-path, linux/arm64=trufflehog,
          --archive-exe-path, windows/amd64=trufflehog.exe,
          --, --no-update, git, file://., --since-commit, HEAD, --results=verified, --fail,
        ]
  - repo: https://github.com/scop/wrun
    rev: v0.4.0
    hooks:
      - id: wrun
        name: Check Woodpecker CI files (woodpecker-cli)
        #info command: woodpecker-cli --disable-update-check --pretty lint --strict --plugins-trusted-clone ...
        pass_filenames: false
        # wrun generate github woodpecker-ci woodpecker
        args: [
          --url, linux/amd64=https://github.com/woodpecker-ci/woodpecker/releases/download/v3.0.1/woodpecker-cli_linux_amd64.tar.gz,  # renovate: datasource=github-releases depName=woodpecker-ci/woodpecker
          --url, linux/arm64=https://github.com/woodpecker-ci/woodpecker/releases/download/v3.0.1/woodpecker-cli_linux_arm64.tar.gz,  # renovate: datasource=github-releases depName=woodpecker-ci/woodpecker
          --url, windows/amd64=https://github.com/woodpecker-ci/woodpecker/releases/download/v3.0.1/woodpecker-cli_windows_amd64.zip, # renovate: datasource=github-releases depName=woodpecker-ci/woodpecker
          --archive-exe-path, linux/amd64=woodpecker-cli,
          --archive-exe-path, linux/arm64=woodpecker-cli,
          --archive-exe-path, windows/amd64=woodpecker-cli.exe,
          --, --disable-update-check, --pretty, lint, --strict,
          --plugins-trusted-clone, '${DOCKER_INTERNAL_REGISTRY}/docker-hub/woodpeckerci/plugin-git',
          --plugins-trusted-clone, '${DOCKER_INTERNAL_REGISTRY}/docker-hub/gecoit84/woodpecker-git-plugin',
        ]
