---
labels:
  platform: linux/amd64
  backend: docker

when:
  event:
    - tag

depends_on:
  - linux-build-and-push
  - windows-build-and-push

skip_clone: true

matrix:
  plugin:
    - git-basic-changelog
  version:
    - latest
    - windows-ltsc2022

steps:
  - name: Add label 'docker-hub'
    image: ${DOCKER_INTERNAL_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-harbor-label-plugin
    pull: true
    settings:
      registry:
        from_secret: DOCKER_REGISTRY
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD
      debug: true
      label: docker-hub
      project: ${CI_REPO_OWNER,,}
      image: woodpecker-${plugin}-plugin
      tag: "${version}"
